# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

# Offense count: 221
Metrics/AbcSize:
  Max: 312

# Offense count: 14
Metrics/BlockNesting:
  Max: 5

Metrics/BlockLength:
  Max: 86
  Exclude:
    - "test/**/*"

# Offense count: 5
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 2000

# some includes are really long
Metrics/ModuleLength:
  Max: 1500

# Offense count: 81
Metrics/CyclomaticComplexity:
  Max: 50

# Offense count: 321
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 501

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

# Offense count: 74
Metrics/PerceivedComplexity:
  Max: 59

# Offense count: 436
# Configuration parameters: EnforcedStyle, SupportedStyles.
Naming/MethodName:
  Enabled: false

# very inconsistent params in old API
Naming/UncommunicativeMethodParamName:
  Enabled: false

# very inconsistent params in old API
Naming/UncommunicativeBlockParamName:
  Enabled: false


# Offense count: 94
Style/Documentation:
  Enabled: false

# Offense count: 97
# Configuration parameters: EnforcedStyle, SupportedStyles.
Naming/VariableName:
  Enabled: false

# Offense count: 1
Style/ClassVars:
  Enabled: false

# Offense count: 20
# Configuration parameters: Exclude.
Naming/FileName:
  Exclude:
    - "src/modules/*"

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false
