#!/bin/bash

# Create international phone codes map
# Michal Svec <msvec@suse.cz>

url="http://www.studyabroad.com/telcodes.html"

echo '/**
 * International phone codes map
 * Author: Michal Svec <msvec@suse.cz>
 * $Id$
 */

{

textdomain "network";

return $['

lynx -dump "$url"				|
	grep '^ \+[0-9]\+ \+[[:alpha:] ]\+ *$'	|
	sed 's|^ *\([0-9]\+\) *\(.*\) *$|    "\2" : "\1",|g'

echo '];

/* EOF */
}'
